### ISSUE TITLE
[QUESTION] Source of "Develop by Tidbyt" apps?

### ISSUE THREAD

**Issue by konecnyna** [tidbyt/community#1262]
Hey all,

I was trying to dig in deeper to some of the Tidbyt develop apps for examples/inspirations for my own app but can only find sources for community apps.

Are the apps developed by the core team (Developed by Tidbyt) private source? Or are they available somewhere to read through the code?

Thanks!

**Comment by rs7q5** [comment]
The source code for apps made by Tidbyt are not publicly available.  There is a community equivalent (at least as far as information displayed) available and there are plenty of examples in the community to use as a base.
