### ISSUE TITLE
Community app merged, but not showing in mobile app for installation

### ISSUE THREAD

**Issue by alewando** [tidbyt/community#1285]
I submitted a new app which was merged a few weeks ago (#1199), but I'm unable to locate it in the mobile app to install to my device. I've seen several other PRs that have been merged since and are visible in the mobile app. Is there anything addtional I need to do to make it available for installation?

**Comment by drudge** [comment]
@alewando Have you signed up for the Beta list yet? I can search for Langton in the mobile app and see your app there.

**Comment by rs7q5** [comment]
They may just do it in batches or something. It just depends. Sure things come up as well. Getting added to beta will help seeing it quicker. 


As for feedback, that's sort of what beta is for, is hoping it can be caught before released to everyone. But there is a new apps app that when it is available on the app it shows up on that app. I don't know if the Tidbyt api endpoint it hits the beta or not, haven't checked. my guess it is not the beta.

**Comment by alewando** [comment]
Ok, thank you. I will close this issue then.
