### ISSUE TITLE
[Feature Request]: States Visited

### ISSUE THREAD

**Issue by rs7q5** [tidbyt/community#1344]
@sloanesturz first off, just came across the states visited app and it looks really good. Nice job!  Any chance there could be like an outline only if you've driven through it like drop-down with options no, driven,visited, or something?

 I guess you'd have to unfortunately add a check for existing installs so if that if config is false (check text would be easiest) then it's none and if it is true then it is visited. That just makes sure existing installations don't break.... I think you could get some even cooler unique states visited maps. 

Also as I typed this I think a toggle for showing the number of states visited/driven would be cool. Let me know what you think.

**Comment by sloanesturz** [comment]
Those features are cool! I fully endorse any and all improvements to the States Visited applet. I don't have much time to hack on Tidbyt right now, but if anyone wants to get their hands dirty, I encourage them!

I'll have more time over the summer and will bounce back to this ticket in a few months if it's still open. Hopefully it's implemented by then :)

**Comment by rs7q5** [comment]
I definitely don't have time to redraw all of them. If there were svg's already existing of outlines the fix would be implemented. It may have to wait until the summer :/ but that isn't that far away either!! Excited to see this happen!

**Comment by sloanesturz** [comment]
The state SVG images are here: https://github.com/tidbyt/community/tree/main/apps/statesvisited/state-images

I think you could make them outline-only by replacing `fill:#______` with `fill:none`. You can then run a slightly-adjusted [helper.sh](https://github.com/tidbyt/community/blob/main/apps/statesvisited/helper.sh#L10) script to create base-64 encodings of the images.

**Comment by rs7q5** [comment]
Hmmm maybe. I have other apps that I'm working on, so may not get to this before you do. But keep me updated on if that does work!
