### ISSUE TITLE
Duolingo app not working

### ISSUE THREAD

**Issue by meejle** [tidbyt/community#1358]
This probably isn't the "done thing", but it's the only way I could think of to ping @saltedlolly and let him know his Duolingo app may be dead. (I don't have Twitter.)

It definitely is for me, I ran it in Pixlet and it was giving me 401 errors.

I _did_ notice it said it might break at any time, and I don't necessarily expect it to be supported...
**BUT,** I'm whiny and entitled and I reallllly want it on my Tidbyt (my SO does, too). 😅

What are the chances of it coming back?

**Comment by saltedlolly** [comment]
Ok, I have had a quick look and the API is still working but they may have changed something. See this test query: https://www.duolingo.com/2017-06-30/users/6364229/xp_summaries?startDate=2023-04-14&endDate=2023-04-24&Europe/London

One thing I notice is that the API query now seems to return the number of sessions completed each day, as well as the total time spent. It never used to include this data before, though I wished it did. I have always found setting an XP target a bit arbitrary, but it was the only option available. I much prefer the idea of setting a target of 5 lessons a day, or 30 mins a day of study. I might look into changing the Tidbyt app to do it this way. What do you think?

I'm pretty busy with other right now but I will get to it when I can.

**Comment by saltedlolly** [comment]
I just pushed a fix, which should hopefully get it working for now. I will look into the improvements mentioned above.

**Comment by meejle** [comment]
Just been testing it out in Pixlet and I think you left in a debug thing?

Line 323:

        params = {
            'username': 'saltedlolly',
        }

Seems like it pretty much only shows _your_ stats in its current state. 😁
But thanks for the quick fix!

I really like your ideas; "minutes a day" seems like a really natural way of doing it. 👍

**Comment by saltedlolly** [comment]
Oops, I already removed that, but I must have for forgotten to update the PR.

**Comment by meejle** [comment]
I think they've killed it again 💔

**Comment by meejle** [comment]
> I'm keen to pick this up and fix it but may need some assistance from someone who has had it working in the past to help test it and get it right.

I'd be happy to help you test it if you're up for it, I miss having it on my Tidbyt! ✌️
