### ISSUE TITLE
Incorrect pressure units for Tempest Weather App

### ISSUE THREAD

**Issue by codylerum** [tidbyt/community#1383]
It appears that the tempest weather flow app as has been replaced with a new version.

Unfortunately it is not showing the correct units for station pressure.

My station is set for `inHg` which would be `30.086 inHg` but it is showing as 1018.8

**Comment by epifinygirl** [comment]
It’s showing up as MB units instead of inHG (conversion is taking the MB and multiplying by 0.02953). I’m hoping to update it quickly when I get a minute.

**Comment by rohansingh** [comment]
I think the issue is just that we lost the `units_pressure` param in the newer version of the app.

**Comment by jvivona** [comment]
it's an API thing.   even when the device is set to inHg
![image](https://user-images.githubusercontent.com/1454249/234384372-83fa5cc9-3d6d-41b6-8c37-0134b5b7fe83.png)

it still returns pressure in mb for /observation/station/<stationid>
but it's correct in /better_forecast.

Let me see if I can figure it out - give me a little bit.

**Comment by jvivona** [comment]
sorry - late to the party..  NVM.
