### ISSUE TITLE
Strava app not working

### ISSUE THREAD

**Issue by Drtrider** [tidbyt/community#1394]
After completing the "Strava Login" field, nothing seems to load for the app. See screen shot.
![borked strava](https://user-images.githubusercontent.com/1545447/235014250-bbcba860-aa56-45e8-977d-b4c103cf91a1.png)

**Comment by rs7q5** [comment]
for future reference it is helpful to cc the original author. cc @rgkimball.

**Comment by rgkimball** [comment]
I believe we've started to hit our rate limit ceiling. I tested everything locally and didn't find issues using my own credentials. 

@rohansingh @matslina Would you guys mind checking with their dev team?

**Comment by rohansingh** [comment]
Yeah unfortunately it's the rate limit. I'm working on getting Strava to raise the rate limit for us.

**Comment by Zkuiper** [comment]
Any update on this? I just got my Tidbyt and basically bought it for this feature.

**Comment by rgkimball** [comment]
> Any update on this? I just got my Tidbyt and basically bought it for this feature.

Hi - have you tried again recently? Mine has been working again recently, I assume Rohan was able to get a higher limit.

**Comment by Zkuiper** [comment]
Yeah been trying today, get the same thing as above. Connects fine, no error, then it just always displays the clock idle screen no stats

**Comment by Zkuiper** [comment]
New update, it randomly starting working in the evening (I changed nothing) but then went back to not working and showing the idle clock logo (I also changed nothing)

**Comment by rgkimball** [comment]
@Zkuiper this is a symptom of us hitting the API ceiling, which is shared by all Tidbyt owners - the more users/screens we service overall, the higher likelihood this will happen. Mark has made some changes recently to help mitigate this, but you can expect it will continue to happen periodically until our overall limit is increased by Strava. The API limit resets once each day, so you may notice the screen work for some period of time in the morning, then stop working (i.e. idle clock logo) once we have made the maximum number of requests that day. 

Caching data for 24 hours is one way we've tried to reduce the number of daily calls we make, but there are practical considerations here: at what point is very stale data not useful to you? 48 hours means even if you record an activity today, you will still see what you recorded 2+ days ago on your Tidbyt. Not a great user experience.

**Comment by Zkuiper** [comment]
Thanks for the explanation. Personally I would guess that even like a 72 hour cache approach would be acceptable for like >80% of users (based on nothing but ~*~Vibes~*~) especially considering the alternative is it being basically non functional. 

Do you get any sort of feedback stats on what percentage of users have the app set to all-time, or YTD, etc? Could give a more based view of who would notice the caching.

**Comment by rgkimball** [comment]
The Tidbyt team would have access to those statistics. Personally I would rather have something like an 8 hour cache, and would be disappointed by anything greater than 24 hours. It's great that we've outgrown our current limit - shows how much people enjoy these apps! Since the Tidbyt applet model here doesn't currently support [Webhooks](https://developers.strava.com/docs/webhooks/) (i.e. when you save a new event, your device receives new data rather than us polling for it), Increasing our request limit is ultimately the answer here.

**Comment by rohansingh** [comment]
Just an update here, we've reached out to Strava to plead our case and request a higher limit. As far as I can tell we are following all of their guidelines, and we have a pretty popular app, so I'm hopeful they raise the limit for us.
