### ISSUE TITLE
Powerball app stopped working 

### ISSUE THREAD

**Issue by mcorby17** [tidbyt/community#1407]
Doesn't work at all anymore, doesn't even appear on my tidbyt. The tidbyt phone app shows a cloud with a line through it.

**Comment by rs7q5** [comment]
cc @AmillionAirs . I believe the api has changed and needs updating.

**Comment by AmillionAirs** [comment]
Yeah the api changed and isn't publicly listed anymore on the powerball website.  Not much I can do at this point as their aren't any other free options

**Comment by AmillionAirs** [comment]
@matslina is there any way to just de list this app? I don't know of any free apis for this information. Unless you guys want to pay for something and just take over the app which I'm totally fine with if you do.
