### ISSUE TITLE
How to pass config values when using `pixlet serve`?

### ISSUE THREAD

**Issue by charliesneath** [tidbyt/community#1465]
The documentation [here](https://github.com/tidbyt/pixlet/blob/main/docs/authoring_apps.md) mentions:

> The config object contains values that are useful for your app. You can set the actual values by:
> * **Passing URL query parameters when using pixlet serve.**
> * Setting command-line arguments via pixlet render.

Can some please provide an example of how URL query params are used in the context of `pixlet serve` with the CLI?

Thank you!

**Comment by radiocolin** [comment]
You put them in the URL in your browser.

Eg: 127.0.0.1:8080/?station=Wayne+Junction&direction=S
