### ISSUE TITLE
Jacket app doesn't indicate how to get API keys

### ISSUE THREAD

**Issue by mcorby17** [tidbyt/community#1559]
@noahpodgurski I think your jacket app would be handy but I cannot figure out where to get the API keys to make it work for my location. There is no documentation on how to get said keys.

Ideally this issue should be resolved by adding documentation. Or at least just tell me where to get the keys :).

**Comment by noahpodgurski** [comment]
Openweather

**Comment by mcorby17** [comment]
For both API key and application key? What's the difference between the two?

**Comment by noahpodgurski** [comment]
Yep, just create an account they give you both

**Comment by mcorby17** [comment]
I have an account... I only have one API key. :/ 
![image](https://github.com/tidbyt/community/assets/12755405/5212e472-ec0e-4123-99c1-14884b4f2604)

**Comment by jaschwa** [comment]
Same issue as @mcorby17

**Comment by noahpodgurski** [comment]
Oh I'm sorry I thought this was on my MR, this is pending changes which will fix it

**Comment by mcorby17** [comment]
New changes work for me 👍. Thanks for the update!
