### ISSUE TITLE
Baywheels GBFS feed changed

### ISSUE THREAD

**Issue by burritojustice** [tidbyt/community#1793]
The Baywheels app is not loading. Seems that Lyft may have deprecated the old Baywheels GBFS feed URLs.

current ones are here: 

https://gbfs.baywheels.com/gbfs/2.3/gbfs.json

I think the station info and station status on lines 16 and 17 need to be updated:

https://github.com/tidbyt/community/blob/c43065da0020ed829fcab21fd86dd23b87b43571/apps/baywheels/bay_wheels.star#L16

https://gbfs.lyft.com/gbfs/2.3/bay/en/station_information.json

https://gbfs.lyft.com/gbfs/2.3/bay/en/station_status.json

(sorry I didn’t do a PR, just got my Tidbyt and don’t have the dev tools set up yet to test…)

**Comment by tavdog** [comment]
the new urls do apparently work. Issueing PR now.

**Comment by matslina** [comment]
Thanks @tavdog !
