### ISSUE TITLE
MLB standings app displaying teams in the wrong order

### ISSUE THREAD

**Issue by jmanske** [tidbyt/community#1849]
The "classic" MLB standings app is displaying teams in the wrong order. If you check this morning, you will see something like this for NL West, having the last place Colorado Rockies in first:
<img width="963" alt="Screenshot 2023-09-12 at 5 44 25 AM" src="https://github.com/tidbyt/community/assets/37538944/9a9aa2f4-2cc9-4d75-920b-6dcc8368d101">

The reason for this is because of how the app tries to sort the teams before displaying them:
```python
stats = entries[0]["stats"]

statNumber = 0
for j, k in enumerate(stats):
    if k["name"] == "gamesBehind":
        statNumber = j
entries = sorted(entries, key = lambda e: e["stats"][statNumber]["value"])
```

The ESPN API does not guarantee you that each each teams "stats" array is in the same order. The code is using the first result to figure out which "stat" the "gamesBehind" entry is, and uses that for every team. This ends up sorting by "games behind" for the first team we got back (Rockies) and "games played" for everyone else.

I can/will fix if original app author gives me permission, or we can send the issue to him.

Editing to tag @cmarkham20 who I think is the original app author.

**Comment by cmarkham20** [comment]
Feel free to submit a fix!

**Comment by jmanske** [comment]
Working on it now!

**Comment by jmanske** [comment]
PR is out to fix this: https://github.com/tidbyt/community/pull/1859
