### ISSUE TITLE
"Jacket" app doesn't update 

### ISSUE THREAD

**Issue by mcorby17** [tidbyt/community#1943]
I've noticed that the "jacket" app will say that I don't need a jacket on my tidbyt when I clearly do. If I check the app on the tidbyt app it says that I DO need a jacket.

Sometimes if I pin the app it will force update and correctly show that I need a jacket.

@noahpodgurski

**Comment by noahpodgurski** [comment]
Hmm, I can't recreate this error. The refresh rate for the app is an hour so that could be why, but if it's an issue with what's showing on the app vs what's currently loaded on your tidbyt, I'm not sure how that works really... Maybe @matslina could fill in here
