### ISSUE TITLE
NHL Live not working

### ISSUE THREAD

**Issue by matslina** [tidbyt/community#2051]
@reedarneson Got a couple of users reporting the nhl-live app is malfunctioning at the moment. Seeing a lot of these errors in logs:
`Error in get: Get "https://statsapi.web.nhl.com/api/v1/schedule?startDate=2023-11-18&teamId=21": lookup statsapi.web.nhl.com on 10.149.0.10:53: no such host`

**Comment by reedarneson** [comment]
Hi @matslina , yes - the NHL dropped a large API change a week or so ago. I have an update underway to migrate to the new one. I plan to have the PR in the next few days.

**Comment by halwebguy** [comment]
@reedarneson FYI, I updated some of my other apps (not Tidbyt). The new API is very similar, but you will want to send a user-agent that looks like a standard browser or they will block the request.
