### ISSUE TITLE
Empire State Building lights - all white, no text

### ISSUE THREAD

**Issue by jvivona** [tidbyt/community#2059]
@sklose - when the building is in "signature white" - there's no text scrolling on the app - makes it look like the app is broke.   Maybe some default text during that scenario?   Didn't see you on Discord - so I figured here was the next best place.

![image](https://github.com/tidbyt/community/assets/1454249/1a9436d3-f1ae-401b-860e-15b37c684489)

![image](https://github.com/tidbyt/community/assets/1454249/fd5c5056-7fdb-4120-878d-0747e95e4305)

**Comment by sklose** [comment]
Thanks for the bug report @jvivona . I pushed a new version of the backend lambda, which should fix the issue. BTW: is there a way to link the backend repository in the manifest file, so it's easily discoverable? https://github.com/sklose/empire-state-colors

**Comment by jvivona** [comment]
Got it - see the change...   closing this one.

@sklose  - When you say "backend repository in the manifest file" - I'm not sure what you are asking - what specifically?   if you are on the discord channel - reach out to me there - it's a better environment for these discussions  (joevivona on Tidbyt Discord https://discord.com/channels/928484660785336380/928485908842426389 )

**Comment by jvivona** [comment]
🔐
