### ISSUE TITLE
[NSWFuelCheck] Adding additional fuel types

### ISSUE THREAD

**Issue by c2342** [tidbyt/community#2196]
Hi @M0ntyP 

Thanks for your awesome work on the NSW Fuel Check app! 

Wondering whether you could add "Premium Diesel (PDL)" to the list of fuel types? It seems the more common one especially in metro areas which also makes it cheaper. 

There is also a list of other types according to https://www.fairtrading.nsw.gov.au/__data/assets/pdf_file/0010/371683/FuelCheck_API_technical_specs_V1.0.pdf

Thanks heaps!
 C

**Comment by M0ntyP** [comment]
Hey @c2342,

Sure thats pretty easy to do! I'll add it on and submit the update and I'll see what else I can add from that PDF

**Comment by M0ntyP** [comment]
FYI - I've added Premium Diesel and Ethanol 94 & 105 now. The PR has been submitted

**Comment by c2342** [comment]
Legend! Thank you so much!

**Comment by M0ntyP** [comment]
No problem! 

Let me know if there is anything else you want to add or change
