### ISSUE TITLE
NYC bus app not showing up in app yet

### ISSUE THREAD

**Issue by samandmoore** [tidbyt/community#231]
Hi!

I saw the NYC bus app that I made was merged a while ago but I'm still not seeing it in the app to setup. I'm seeing some other apps merged around the same time though. 

Is there an issue with the bus app preventing it from getting enabled?

Thanks!

**Comment by rohansingh** [comment]
Hi Sam. Unfortunately the app doesn't seem to be rendering for any of the stops that I tried when testing:

![Screenshot_20220304-211701](https://user-images.githubusercontent.com/615175/156867341-abbd971a-2686-4f2b-9b53-525096e85f1d.png)

**Comment by samandmoore** [comment]
That's odd! Let me investigate. It's weird because I have been running it locally for a month. Though not through with the schema layer on top. 

Does it log anything when it doesn't render? I'd expect that the API must be erroring or it's failing to decrypt the secret?

**Comment by rohansingh** [comment]
The secret definitely decrypts and works fine since we're able to see the list of stops and pick stops. Here's the error log:

![Screenshot_20220305-065259](https://user-images.githubusercontent.com/615175/156886413-d39b5c22-d900-4eb0-bafa-a5f56902b176.png)

**Comment by rohansingh** [comment]
I see the same things with all the stops I've tried around our office at 544 Park Ave in Brooklyn.

**Comment by samandmoore** [comment]
weird! I'm running it locally right now with that stop and it's working 😬 

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/407586/156886448-aeac7e64-03b5-4c64-aff1-622cf9ddc837.png">

**Comment by samandmoore** [comment]
lemme look closer at the bus API responses to see if there's some reason that key might be missing.

**Comment by rohansingh** [comment]
OK, head scratcher for sure. There must be something with our server environment that's different. I'll have to try it on my dev server and report back.

**Comment by rohansingh** [comment]
OK, head scratcher for sure. There must be something with our server environment that's different. I'll have to try it on my dev server and report back.

**Comment by rohansingh** [comment]
The preview with example stop code works so there might be some issue in how we're propagating the config.

![Screenshot_20220305-070108](https://user-images.githubusercontent.com/615175/156886638-84465eac-ceb4-4f48-98b8-5b7504268213.png)

**Comment by rohansingh** [comment]
OK, I see the issue. Please check out the last bit in the documentation for `LocationBased` that shows what to expect from `config.get`:
https://github.com/tidbyt/pixlet/blob/main/docs/schema/schema.md#locationbased

Here's an example of how this is handled in the LIRR app:
https://github.com/tidbyt/community/blob/4b9b58b085d35042b6e392b4efd226024bc8db47/apps/lirr/lirr.star#L28

**Comment by samandmoore** [comment]
ah crap! that's my bad. missed that in the docs. will fix that up right now.

**Comment by betterengineering** [comment]
This has been launched! Thanks again @samandmoore and so sorry for the back and fourth.
