### ISSUE TITLE
Clarify how often PRs will be reviewed in README

### ISSUE THREAD

**Issue by mokolodi1** [tidbyt/community#2321]
Given that one of Tidbyt's main features is that it's developer friendly, I think it's reasonable to expect relatively quick turnaround time for PRs submitted to this repo.

Looking at currently open and recently closed PRs, there have been no approvals of new apps or fixes (or comments on them by Tidbyt developers) since at least February 8th, 2024, almost a full month ago. (The oldest PR open is currently #2261.) 

It would be helpful to add a section in the [Contributing Changes section of the README](https://github.com/tidbyt/community?tab=readme-ov-file#contributing-changes) clarifying the cadence with which developers can expect their changes to be reviewed and approved. Other important business work is clearly taking priority, and that's okay, but setting expectations around this up front would ease the frustration of a PR sitting around for weeks. (I opened #2276 23 days ago.)

[Another frustrated developer](https://github.com/tidbyt/community/pull/2274#issuecomment-1940358552) from 23 days ago:
>Just curious how long it is going to take to publish this. I'm really dying to use it on my Tidbyt. It's the missing experience and the reason why I bought this thing.

**Comment by quacksire** [comment]
+1

**Comment by logandeal** [comment]
+1

**Comment by mokolodi1** [comment]
Another thing to note: I would plug the private app hosting option in the app as a way to allow devs to start enjoying their apps immediately. I didn’t know it existed until just now, but I happily would have shelled out $5 a month ago until my PR was approved (which just happened btw—yay!)

**Comment by jmanske** [comment]
Private apps are also great for testing out something in "real life" before submitting a PR. If I submit a PR and my app has an issue, I have to make another one to fix it. Easier to just work out the kinks before the submission.

**Comment by mokolodi1** [comment]
Context on why PRs are taking forever: https://github.com/tidbyt/community/pull/2270#issuecomment-2000004021

> We're doing a lot of work on Tidbyt Gen 2 right now, and the community repo suffers as a consequence.

**Comment by matslina** [comment]
Hey guys. We hear you and feel you. Our ambition has been to review PRs weekly, usually on Thursdays, but as @mokolodi1 mentioned this has been completely thrown out of whack by the ongoing work on Gen 2. I think it would be best to hold off on documenting review cadence until we're through the bulk of the Gen 2 work.

As @jmanske mentioned, we hope that private apps can be part of the solution here, but also totally get that it's not the same thing as having your work published for the world to see.

**Comment by mokolodi1** [comment]
No worries, @matslina. I appreciate all your hard work on Gen 2, and holding off on documenting the future cadence makes sense. (I'm personally excited to get a Gen 2 given the new features, so I appreciate your work in fixing the bugs before I do!)
