### ISSUE TITLE
NHL Live App Issue

### ISSUE THREAD

**Issue by epifinygirl** [tidbyt/community#2335]
The NHL Live app doesn’t show live scores so I assume the api was changed a bit to cause the issue. The app will show the time the game starts until the game is over, then it will show the final score.

**Comment by jmanske** [comment]
The API JSON response must have changed (or, I can't imagine it ever worked if it's always been like this so I assume it has changed). 

The "teamGameStats" node looks like this:
`
       "teamGameStats":[
          {
             "category":"sog",
             "awayValue":28,
             "homeValue":38
          },
          {
             "category":"faceoffWinningPctg",
             "awayValue":0.508772,
             "homeValue":0.491228
          },
          {
             "category":"powerPlay",
             "awayValue":"1/2",
             "homeValue":"1/4"
          },
          {
             "category":"powerPlayPctg",
             "awayValue":0.5,
             "homeValue":0.25
          },
          {
             "category":"pim",
             "awayValue":8,
             "homeValue":4
          },
          {
             "category":"hits",
             "awayValue":20,
             "homeValue":18
          },
          {
             "category":"blockedShots",
             "awayValue":16,
             "homeValue":18
          },
          {
             "category":"giveaways",
             "awayValue":5,
             "homeValue":9
          },
          {
             "category":"takeaways",
             "awayValue":6,
             "homeValue":7
          }
       ],
`
Thus the app fails to render whenever a game goes live which is why it is "stuck" on the previous image.

I could fix it if I got permission from @reedarneson (or he can fix it of course!).

**Comment by reedarneson** [comment]
Hi, apologies for the delay, just saw this issue. I just did a quick check and it looks like the API did change in more than one way. Fixed a couple already (including the above, thanks jmanske. Doing some testing/watching here for a bit and I should have a PR out soon.

**Comment by reedarneson** [comment]
PR was merged this morning. I'm seeing Live game updates again. I have a couple other somewhat minor fixes I need to do when I get time - relating to the situationCode status and game start time/cache. Hopefully soon.
