### ISSUE TITLE
Base64 decoded images look worse today than yesterday

### ISSUE THREAD

**Issue by jmanske** [tidbyt/community#2356]
Did something change about how pixlet is decoding base64 encoded images? They look worse today than they ever have. @matslina

**Comment by rohansingh** [comment]
@jmanske Probably my fault. Do you have an example?

**Comment by jmanske** [comment]
The "FlyTheL" app images are all pretty "blocky" now. They are 32x32 pixel perfect logos but I compress them down a few pixels in the call to render them. 

They looked pretty good up until some point today but now almost look like they are missing pixels today.

**Comment by jmanske** [comment]
Those logos look very different and worse than they looked yesterday. 

Brewers might be the most glaring example.

Here's a picture I took of the app a few days ago:
![image](https://github.com/tidbyt/community/assets/37538944/a465ced8-790c-4916-b989-982b4eb384e1)

**Comment by rohansingh** [comment]
Thanks! I can clearly see the issue with the Brewers.

Rolling back the new renderer now, things should be fixed within the next few minutes.

**Comment by jmanske** [comment]
lol, something not being respected right....
![image](https://github.com/tidbyt/community/assets/37538944/22f9ca42-5a01-4cfd-b278-b0b1f230d3c3)

**Comment by rohansingh** [comment]
Fixed by tidbyt/tidbyt#6487.

**Comment by rohansingh** [comment]
Fix is out now, looks correct again.
