### ISSUE TITLE
Severe Weather app

### ISSUE THREAD

**Issue by GITHUB-139** [tidbyt/community#2369]
Please updated font to tom-thumb, the selected font is hard to read, I loaded it locally, modified and pisplayed in pixlet serve, tom-thumb works good, and line not on top of each other.
```
    ## Main Alert Text
    mainAlertText = alert["properties"]["event"]

    mainAlertTextWrappedWidget = render.WrappedText(
        content = mainAlertText.upper(),
        align = "center",
        font = "tom-thumb",  # tiny
        color = "#FF0000",  # red
    )
```
See attacked zip webp from export on pixlet serve
[tidbyt-preview-1712115255238.webp.zip](https://github.com/tidbyt/community/files/14846392/tidbyt-preview-1712115255238.webp.zip)

**Comment by GITHUB-139** [comment]
Cummunity app name:  severewxalertsusa.star

**Comment by jmanske** [comment]
Might also be a solution to use the `linespacing` attribute in the WrappedText widget to make things a little more readable. Let's tag the app author @rs7q5 to see what he thinks!

**Comment by rs7q5** [comment]
What is the original font?

I am not the original author. That would be @aschechter88. I don't think it's super hard to read and you also have to make sure to account for almost all scenarios or longer names. 

One possible option though that I don't think the author would care about would be to just add a simple font config of small/large texts (instead of all options). That I think would satisfy all parties.

**Comment by GITHUB-139** [comment]
Original:CG-pixel-3x5-monoPROPOSED#tom-thumbThe spacing concerned mention is moot in irrevelent as in test unfact the tom-thumb actually is more efficient and will display more info so in yesterdays alerts with original: “FOG ADVISERY” on disply showed fog one first line adverisery on second line smoshed together  (Hence hard to read)  format 4x5x4x5x0 the proposed actually fit the full alert on line on (4x6x4x4x1) on the second alerts with was three lines on original font also three lines new font same three lines with one pixel space between the lines so gtheir not smashed together, I can only assume the author didnt set tom-thun oraginanly if it wasnt created yet as effectly they both will effectly only give 4 lines in the pane defined for the message.so to the other comment then sime if you want that original font fine allow font choice tom-thumb or the CG in the options, but realistically the cg3x5 is bad choice.Send from ***@***.*** Apr 4, 2024, at 6:18 AM, rs7q5 ***@***.***> wrote:﻿
What is the original font?
I am not the original author. That would be @aschechter88. I don't think it's super hard to read and you also have to make sure to account for almost all scenarios or longer names.
One possible option though that I don't think the author would care about would be to just add a simple font config of small/large texts (instead of all options). That I think would satisfy all parties.

**Comment by jmanske** [comment]
Setting `linespacing = 1` on the WrappedText widget does fix the problem you are describing with the lines being too close together. Current state:
<img width="909" alt="Screenshot 2024-04-05 at 5 19 37 AM" src="https://github.com/tidbyt/community/assets/37538944/8fe09fac-1f2b-4831-a811-4ff408aff973">

With `linespacing = 1`
<img width="929" alt="Screenshot 2024-04-05 at 5 18 38 AM" src="https://github.com/tidbyt/community/assets/37538944/2c6afde7-b96a-4606-97c7-0038564580a3">
<img width="940" alt="Screenshot 2024-04-05 at 5 24 06 AM" src="https://github.com/tidbyt/community/assets/37538944/321488c5-d481-4227-904b-bfcf6b8b188e">
<img width="922" alt="Screenshot 2024-04-05 at 5 24 21 AM" src="https://github.com/tidbyt/community/assets/37538944/0dfa2397-8738-4838-b850-5c518af28447">

Switching it to `tom-thumb` makes W, M, and N nearly indistinguishable from each other so I can understand why the developer may not have picked it. 
`tom-thumb`:
<img width="914" alt="Screenshot 2024-04-05 at 5 26 09 AM" src="https://github.com/tidbyt/community/assets/37538944/dcf11b64-4fdf-42a4-a55b-f0d8da71685b">

<img width="922" alt="Screenshot 2024-04-05 at 5 26 32 AM" src="https://github.com/tidbyt/community/assets/37538944/9f756f33-4fc9-4585-a6f2-3fbdbf5aec30">

If it were my app, my preference would be to leave the font the same and change the `linespacing` to 1.

**Comment by GITHUB-139** [comment]
Ok, Let me try it locally setting the linespace, where did you put the linespace tag?  Net however, the code should be corrected, either way the best.  I’ll check how linespacing shows inn HDK later tonight.Send from ***@***.*** Apr 5, 2024, at 5:28 AM, Jake Manske ***@***.***> wrote:﻿
Setting linespacing = 1 on the WrappedText widget does fix the problem you are describing with the lines being too close together. Current state:
Screenshot.2024-04-05.at.5.19.37.AM.png (view on web)
With linespacing = 1
Screenshot.2024-04-05.at.5.18.38.AM.png (view on web)
Screenshot.2024-04-05.at.5.24.06.AM.png (view on web)
Screenshot.2024-04-05.at.5.24.21.AM.png (view on web)
Switching it to tom-thumb makes W, M, and N nearly indistinguishable from each other so I can understand why the developer may not have picked it.
tom-thumb:
Screenshot.2024-04-05.at.5.26.09.AM.png (view on web)
Screenshot.2024-04-05.at.5.26.32.AM.png (view on web)
If it were my app, my preference would be to leave the font the same and change the linespacing to 1.

**Comment by jmanske** [comment]
It's in the same spot you changed the font in your first post. Instead of changing the font, add the linespacing attribute.

**Comment by jmanske** [comment]
I made a draft PR if you want to take a look. If you're good with it, I can submit it. #2376
