### ISSUE TITLE
[PagerDuty] Oncall endpoint is limited to 25 by default

### ISSUE THREAD

**Issue by nchieng** [tidbyt/community#239]
cc @drudge
Thanks for such a useful applet. 

The functionality to show Oncall status may not work as expected if there are more than 25 on-call schedules on your PagerDuty account.

The `/oncall` endpoint, when no `limit` param is specified is paginated to just 25 results. And your shift may be detailed in later results.
![image](https://user-images.githubusercontent.com/29188449/157146973-46964726-c1dd-4bdc-b04a-ed34ad39fcc9.png)

The max `limit` you can specify is 100, which may not be sufficient on PD accounts with more on-call schedules than that.
![image](https://user-images.githubusercontent.com/29188449/157146921-452b2d91-e30b-4e38-a3d0-f364878b0e2a.png)

For the purpose of determining if the current user is on-call, could we either:
* specify `user_ids[]=profile['id']` to only list the current user's on-call schedules? (This is still limited to 25, which may cater for the majority of PD users, unless they are part of a NOC).
* paginate to following pages if `more: true`? (could impact performance)

**Comment by drudge** [comment]
Hi @nchieng, thanks for submitting your issue. I've submitted PR #241 to address your feedback. Once reviewed and merged by the Tidbyt team, it should page through all on-calls when determining if a user is on call or not.

**Comment by nchieng** [comment]
Thank you so much @drudge
