### ISSUE TITLE
Pull request review?

### ISSUE THREAD

**Issue by knauerhase** [tidbyt/community#2492]
Hi.  I wrote a simple app for Pride month and checked it in with a PR (#2491) last weekend.  Do we need to ask anyone to look at it for approval, or do they just get around to it?  @matslina is listed as an automatic reviewer.

**Comment by jmanske** [comment]
They will get around to it. They usually review them on Thursdays but sometimes it takes longer.

**Comment by matslina** [comment]
Hey. First of all, thanks for the PR. Second, apologies for the slow review time. Like @jmanske wrote we try to get through PRs once a week, but we've had a lot on our plates recently and are lagging behind.

**Comment by matslina** [comment]
Also: Happy Pride!

**Comment by knauerhase** [comment]
@matslina not a problem -- was just my first time through the process for this device.

Do approved apps go into the Tidbyt app for people to find?
