### ISSUE TITLE
Netatmo App Requires Daily Sign-in

### ISSUE THREAD

**Issue by tlatkins** [tidbyt/community#2521]
For the last several months the Netatmo app will require me to remove the app from my Tidbyt on a daily basis and add it back, authenticating to my Netatmo account when I do. If I don’t do that, the app doesn’t even show on my Tidbyt anymore. It appears as if the session is timing out but the app doesn’t refresh the token. @danmcclain @rohansingh I love the app. If I knew how to fix it, I would.

**Comment by danmcclain** [comment]
I think Netatmo changes some of their auth infra, as Carrot Weather recently released a fix for Netatmo weather stations as well (my weather station stopped popping up in Carrot ahead of the update)

When I get time, I can dig in, it should hopefully be a simple fix with the auth url

**Comment by jmrseattle** [comment]
This is SO frustrating -- I had a custom site that pulled info from my netatmo setup here and when they broke it the second time messing with the API and auth I gave up and shut it down.  When it's time to replace this stuff I won't be buying netatmo again.

**Comment by tlatkins** [comment]
I was having to sign in every day to get the Netatmo Tidbyt app working but now even signing in doesn’t work. It seems that it is not connecting to the Netatmo API. All I see in the Tidbyt app for it is the cloud icon with the slash through it.
