### ISSUE TITLE
last.fm app displays time in UTC, not in local timezone

### ISSUE THREAD

**Issue by mashedkeyboard** [tidbyt/community#2610]
Hi folks!

The last.fm app in the repository, when it has its clock function toggled on, seems to be displaying UTC time rather than local time - but the documentation in the app settings for that toggle says it should display local time. For instance, it's just gone 8pm here in the UK right now (British Summer Time, UTC+1), but it displays just past 7pm.

I'm not clear on whether the Tidbyt API actually offers a way to retrieve the time in the current timezone? Other similar clock apps in the repo seem to have either timezone or location settings separately. Does one need to be added, or is there a simpler fix?

**Comment by mashedkeyboard** [comment]
@my-ugly-code - hi! I think you're the original author of the last.fm Tidbyt app. I note from the contributing guidance that changes are subject to approval from the original app author - would you be happy with a timezone setting being added? :)

**Comment by my-ugly-code** [comment]
If other clock apps display correctly for you, yes, just implement what they're doing...seems to be .in_location(). I'm ok with whatever addition is needed to support TZs.

I'm guessing the function handles seasonal adjustments like Summer Time (DST in US). I'm in Eastern US and it's always 'just worked' for me,.

**Comment by danielsitnik** [comment]
Yes, to get the timezone for the device's location configured in the mobile app you just do `config.get("$tz")`.
It's always a good idea to have defaults if things change in the future, so something like `config.get("$tz", "America/New_York")` would work.

**Comment by dtseiler** [comment]
Yep I've done something similar. Is there a guide that mentions $tz? Are there other similar special variables that would be good to know about?

**Comment by danielsitnik** [comment]
Sadly it's not mentioned in the documention.
There's even a PR https://github.com/tidbyt/tidbyt.dev/pull/620 open since june to add it there. 😢

**Comment by dtseiler** [comment]
Thanks, I've added a note there about testing it as well.
