### ISSUE TITLE
Londonbusstop cannot find stops that are already listed in the app

### ISSUE THREAD

**Issue by Esad-np** [tidbyt/community#2656]
@dinosaursrarr Trying to use the app, and put my location in settings. the app then finds 4 bus stops for me to select. Regardless of which one I select, I have error Unknown Stop 
log: [app-id] TFL StopPoint search result does not contain stop code.

**Comment by dinosaursrarr** [comment]
Thanks for flagging this, I wasn't aware. 

I suspect something has changed with the API format. It's possibly related to the recent TfL cybersecurity incident, but probably not. 

I'll look into it this week.
