### ISSUE TITLE
[duolingo] Duolingo app only uses default timezone (London)

### ISSUE THREAD

**Issue by dtseiler** [tidbyt/community#2663]
I just started using the app this week. I've noticed that it was saying I hadn't done any lesson that day when I had. I read your note that it should refresh every 20 minutes but that didn't seem to be it. I then changed to weekly view and it was flashing on Saturday when it is currently 6:30 PM on Friday evening for me (USA central daylight time).

I have my location set in my Tidbyt app preferences but apparently the Duolingo app isn't using that or unable to read that?

I see [where it _should_ be reading it and defaulting to the `DEFAULT_TIMEZONE`](https://github.com/tidbyt/community/blob/main/apps/duolingo/duolingo.star#L322) of "[Europe/London](https://github.com/tidbyt/community/blob/main/apps/duolingo/duolingo.star#L22)".

Just wondering if it's the app or maybe something else I didn't set. I'm a new Tidbyt user. This is on a Gen2, app is on Android.

**Comment by dtseiler** [comment]
Perhaps I'm mistaken in assuming that Tidbyt or duolingo widget would be determining the timezone based on my specified location. I don't specify timezone anywhere in the Tidbyt app or duolingo settings. I only specify my location (city).

**Comment by dtseiler** [comment]
I set up the dev kit and played with changing the default to force it for now. I'm not sure if there's supposed to be a config drop-down for timezone or what `config.get(timezone)` is expected to retreive yet. Even so when I query now for my user, the latest value only has date `1726272000` which is Fri Sep 13. Today is Sat Sep 14 and I've done my lessons nearly 12 hours ago. I'm curious if there's a known delay from Duolingo that would explain the gap.

**Comment by dtseiler** [comment]
@saltedlolly Not sure if it's bad form to ping the developer directly (apologies if so), but curious if you've encountered similar problems. It seems like, regardless of the timezone issue, there is some lag or gap in what Duolingo provides via that query API.

**Comment by saltedlolly** [comment]
Hi, the truth is I built this for myself several years ago and it is a long time since I looked at it. I've pretty much forgotten how it works even though I built it and would need to dig into it. Since I am in the UK on London time this is not an issue that I have encountered personally. Someone else was mentioning this issue on the Tidbyt support site (perhaps that was you?). If I had time to look into it, I would, but I just don't right now. Sorry. By all means make a PR if you can figure out the issue.

**Comment by dtseiler** [comment]
That might have been me if it was this past weekend. I was enjoying getting into the code, just wanted to touch base and see if there wasn't something already being looked it so I'm not re-inventing any wheels as I stumble around.

The obvious solution is for me to simply move to London.

**Comment by dtseiler** [comment]
I wonder if we can do [something like this](https://github.com/tidbyt/community/blob/main/apps/clockbyhenry/clock_by_henry.star#L56-L64) to grab the timezone from the tidbyt device settings.

```
    location = config.get("location")
    location = json.decode(location) if location else {}

    timezone = location.get(
        "timezone",
        config.get("$tz", DEFAULT_TIMEZONE),
    )
```

**Comment by dtseiler** [comment]
hmm it seems maybe that would just reference a local config to this app. I'm hoping there's a way to see the location that I've set in the device settings. Seems silly to have every app separately store the same location and/or timezone. I don't recall setting it for that clock.

**Comment by dtseiler** [comment]
nixelclock did not prompt me to set location (and has no such separate config). It grabs timezone from `$tz`?

https://github.com/tidbyt/community/blob/main/apps/nixelclock/nixel_clock.star#L230
```
timezone = config.get("$tz", DEFAULT_TIMEZONE)  # Utilize special timezone variable
```

I'll look into this later and play around

**Comment by dtseiler** [comment]
So that does seem to work for getting the `$tz` value (can be set on the query string in the emulator browser). This also revealed that there is something off with the daily calculation from the json. Right now the app has everything 1 day off. For example, it says I've done 0 today, 175 xp yesterday, and 90 the day before, going to back to a missed day last Thursday. In reality I have 175 today, 90 yesterday and I missed last Friday.  I'll see what I can dig up there.

**Comment by dtseiler** [comment]
Added some debug statements to find this issue:
```
[app-id] time_of_first_entry_unix_time: 1727827200
[app-id] time_of_first_entry: 2024-10-01 19:00:00 -0500 CDT
[app-id] date_of_first_entry: 2024-10-01
[app-id] date_now: 2024-10-02
```
I think Duolingo is being funky with the epoch time on that. Because that entry in the json is definitely for today. That [timestamp is midnight of Oct 2](https://timestamp.online/timestamp/1727827200), so for that I don't think we want to convert to timezone again.

**Comment by dtseiler** [comment]
If I add `in_location("UTC")` so that it doesn't skew things around to this line, then things line up as I would expect:

```
time_of_first_entry = time.from_timestamp(time_of_first_entry_unix_time).in_location("UTC")
```

now I see this:
```
[app-id] time_of_first_entry_unix_time: 1727827200
[app-id] time_of_first_entry: 2024-10-02 00:00:00 +0000 UTC
[app-id] date_of_first_entry: 2024-10-02
[app-id] date_now: 2024-10-02
[app-id] Date of the most recent XP data: 2024-10-02   (No dummy data needed for today.)
```

Basically before it was inserting the dummy data for today because it thought the latest data was for yesterday.

**Comment by dtseiler** [comment]
It also seems like specifying the `timezone` on the Duolingo query string doesn't change anything. I'm not sure what it's supposed to do. The epoch values for each day are the same if I have America/Chicago or Europe/London. /shrug

**Comment by dtseiler** [comment]
I just did a couple lessons just before 9am US CDT. The Duolingo summary json shows it shortly after with a `date` value of `1727913600`, which converts to midnight Oct 3, as expected. Waiting a few minutes for the duolingo applet cache to expire to see if it picks up the change now.

**Comment by dtseiler** [comment]
PR is up (#2766). Not sure how long it usually takes for manual review but so far it seems to fix the time shift changes I've been experiencing.
