### ISSUE TITLE
[datadog] not working?

### ISSUE THREAD

**Issue by tmm1** [tidbyt/community#2736]
are DataDog Monitors and Datadog Charts still working?

on "Datadog Charts" i only see "Forbidden" even though I confirmed my api and app keys work

on "DataDog Monitors" it says "Cannot connect to DataDog" and doesn't let me pick the site (us1, us5, etc)

cc @gabe-ochoa @Cavallando

**Comment by Cavallando** [comment]
Hey @tmm1! Thanks for flagging, they should still be working I don't believe the API has changed based on [DataDog docs on the Monitors endpoint. ](https://docs.datadoghq.com/api/latest/monitors/#monitors-search)

Do you have more details? Are you able to see an error? Also you mentioned you need to pick the site, the app doesnt currently support that (but happy to add it), maybe that could be the issue?

It's also possible the Application Key doesn't have the right authorization scope set for accessing (ie. `monitors_read`).  [DataDog's Postman collection](https://docs.datadoghq.com/getting_started/api/) might show some more detailed error

**Comment by tmm1** [comment]
I verified the key and the constructed URLs and a bunch of stuff. The error is just Forbidden

I'm starting to suspect perhaps datadog has blocked the tidbyt servers?

Is it working for you?

**Comment by Cavallando** [comment]
Just tested with my credentials and the Monitors app is still working for me in TidByt

**Comment by tmm1** [comment]
Thank you for trying it out. I set it up locally and had the same problem, and was able to find and fix the bug in #2744

**Comment by Cavallando** [comment]
Ah nice! Looks like it was an issue with the site then, default site worked fine for my account, thanks for adding that feature!
