### ISSUE TITLE
Strava Applet Not Displaying Correctly in App Preview or Tidbyt Display

### ISSUE THREAD

**Issue by OrianTheHunter** [tidbyt/community#299]
The Strava applet is not displaying correctly on either my Android app or physical Tidbyt.  I am able to select the Strava applet and connect my account but no preview is displayed within the application and once I save and add to Tidbyt it does not display on the actual Tidbyt device as expected in the applet rotation order (it simply skips over it).  Is anyone else experiencing issues with the Strava applet integration?  Or could this be Strava account security settings or something impacting the Tidbyt connection?
![Screenshot_20220328-140356](https://user-images.githubusercontent.com/102548060/160460999-cac0a04b-e9f9-40e5-9ef2-257912653a58.png)
![Screenshot_20220328-140417](https://user-images.githubusercontent.com/102548060/160461020-6e6712b5-2c1d-4467-bdee-cb153f69ee61.png)

**Comment by rgkimball** [comment]
Hey @OrianTheHunter, developer of the Strava applet here - thanks for the report.

Mine had been working earlier today presumably using cached data, but I just removed and re-added my own screens and had the same experience as you - black screen, skipped in the rotation. The demo data flashes briefly once I log in but as soon as it tries to grab my data it seems to crash.

I don't have the official API secrets but tried using my own ID/key locally and was able to pull data in again:

![image](https://user-images.githubusercontent.com/7003930/160476839-42a83901-3b02-4578-904b-b1f65546058d.png)
I suspect this means we've hit the [rate limits](https://developers.strava.com/docs/rate-limits/) - the default setting is 100 requests per 15 minutes and capped at 1,000 requests per day - it's very possible that the community has hit the level of installs that breaches these limits. I was able to reproduce the error locally by disabling the cache and refreshing until I hit the limit using my own API keys. If this is also what's causing the issue on device, the app should begin working again tomorrow and Tidbyt will need to reach out to Strava to resolve - I'm sure apps like VeloViewer have much higher limits than what's available by default!

In the interim, I'll be submitting a PR to replace the `fail` statements in the code with an error message so users aren't left in the dark when this type of thing happens You would see a screen like this instead:

![gif](https://i.imgur.com/5uX25ij.gif)

Sorry for the interruption, hope we'll get everyone back online shortly!

**Comment by OrianTheHunter** [comment]
Hi @rgkimball, 

Thanks for the quick response and thanks for making the Strava applet!  It's great motivation to see right before I start biking after work.  I am not sure if it is a long term solution because of the rate limit as you described but it does appear to be working for me this morning (I just don't know how long that will continue to be the case).

I think this fix should be enough to close this issue, but while I have you I wanted to also provide two other issues/feature suggestions:

1. The number of rides/miles seems to be off by one between what the Strava app is reporting and what the Tidbyt display is showing (The Tidbyt has one less ride than the actual from Strava).
![Screenshot_20220329-072634](https://user-images.githubusercontent.com/102548060/160601762-fd57250a-9def-429f-acd5-15663ff77da6.png)
![PXL_20220329_112826529](https://user-images.githubusercontent.com/102548060/160601777-035f7f9e-2afa-49fd-9a9c-8a5b6e88b223.jpg)

2. Would it be possible to include a toggle to hide the elevation field?  I do not believe exercise bikes/programs such as Peloton/iFit/etc. report elevation to Strava, so it simply shows as a zero.

**Comment by OrianTheHunter** [comment]
I don't know if you can access it for a filtered period of time (such as All-Time stats or YTD Stats) but individual rides do have a Avg Speed value (in mi/h).  If the API can easily show an Avg Speed for multiple ride sessions over different time periods (All-Time/YTD/etc) I think that would be the best to replace elevation with just because it would be applicable to the widest number of scenarios/users.  If not just hiding the elevation line if it == 0 would also be a straightforward visual improvement .

**Comment by rgkimball** [comment]
Great suggestion! I can certainly calculate the average speed from the distance and moving time provided (mi or km per hour).

May be some time before the change is able to be released given the current backlog but I will find time to implement this and submit for review. Thanks again for the feedback - let me know if you have other ideas!
