### ISSUE TITLE
Built-in Clock Applet Not Updating Automatically 

### ISSUE THREAD

**Issue by OrianTheHunter** [tidbyt/community#303]
The built-in Clock applet is not updating automatically (see attached picture showing difference between network clock and Tidbyt clock times).  It is possible to force update the time using the below steps but doing so does not cause the clock to start updating automatically again:

1. Let clock get behind correct time
2. Update Clock applet settings (enable/disable Display Location, 24 hour clock, etc.)
3. Save Changes
4. Observe that Clock updates to display correct time when enabling the above changes but then does not update automatically again
![PXL_20220330_131929346](https://user-images.githubusercontent.com/102548060/160845498-26873697-afca-4dc7-a5d9-24033c0f0820.jpg)

**Comment by matslina** [comment]
Hey. If your device is still in this state, could you shoot us an email at hello@tidbyt.com including the device ID? Would like to take a look at why it's not updating correctly.

**Comment by OrianTheHunter** [comment]
Mats worked with me directly to resolve this issue and time updating is now working as expected.
