### ISSUE TITLE
Option to truncate price on cryptotracker to disable scrolling

### ISSUE THREAD

**Issue by cgrin** [tidbyt/community#357]
There's not a ton of value in having the cents portion of a bitcoin price when the price itself is already five figures. Would be nice to have a toggle (or just truncate by default over 10k, honestly) to disable the scrolling.

**Comment by cgrin** [comment]
Seeing now this can also affect the price delta, right now BTC is down 244.13 and that's wide enough to make it scroll. `display_symbol()` is using the same width of 34 as the price below, even though all of the available symbols are only three characters (https://github.com/tidbyt/community/blob/9761e1aa27dfc98c5b93f8c6103b391da3a5b1d4/apps/cryptotracker/crypto_tracker.star#L29). It would make sense to give more width to that price delta , as it stands about 25% of the line is unused.

**Comment by ethanfuerst** [comment]
this is a good idea, I will look in to it

**Comment by ethanfuerst** [comment]
> Seeing now this can also affect the price delta, right now BTC is down 244.13 and that's wide enough to make it scroll. `display_symbol()` is using the same width of 34 as the price below, even though all of the available symbols are only three characters (
> 
> https://github.com/tidbyt/community/blob/9761e1aa27dfc98c5b93f8c6103b391da3a5b1d4/apps/cryptotracker/crypto_tracker.star#L29
> 
> ). It would make sense to give more width to that price delta , as it stands about 25% of the line is unused.

IIRC I did this to future proof for the option to display the full coin name

**Comment by cgrin** [comment]
Makes sense. Can the widths be defined dynamically? If so you could do something like `ticker_width = min(34, 5*len(ticker_symbol))` and then `delta_width = 63 - ticker_width`

**Comment by ethanfuerst** [comment]
@cgrin opened a pr, lmk your thoughts. I don't want to change the widths of the price change marquee render, as my initial goal with this app is to mirror the existing stock app as closely as possible.

**Comment by cgrin** [comment]
Looks great!
