### ISSUE TITLE
Provide "Color" picker as schema type

### ISSUE THREAD

**Issue by joeyhoer** [tidbyt/community#39]
For apps which allow colors to be customized, it would be helpful if there was a color picker option available within schema. Right now, it appears that the best option is to utilize a list of predefined values with a `dropdown` schema.

```
  colors = [
    {"text": "White", "value": "#fff"},
    {"text": "Red", "value": "#f00"},
    {"text": "Green", "value": "#0f0"},
    {"text": "Blue", "value": "#00f"},
    {"text": "Yellow", "value": "#ff0"},
    {"text": "Cyan", "value": "#0ff"},
    {"text": "Magenta", "value": "#f0f"},
  ]
…
    {
      "type": "dropdown",
      "id": "color",
      "icon": "palette",
      "name": "Color",
      "description": "The color to display.",
      "options": colors,
      "default": DEFAULT_COLOR,
    },
```

My ideal state would be to have the Tidbyt controlled via HomeKit, and use HomeKit to set the color of the display. As long as the app accepts a single color variable, I believe this should be possible.

**Comment by LukiLeu** [comment]
There was one added a few weeks ago: [https://tidbyt.dev/docs/reference/schema#color](https://tidbyt.dev/docs/reference/schema#color)

**Comment by tavdog** [comment]
Time to close as completed ?
