### ISSUE TITLE
Expose "Day/Night" magic variables

### ISSUE THREAD

**Issue by joeyhoer** [tidbyt/community#40]
Some app developers may want to provide a different theme/content at night. Currently app developers must utilize an API to determine daytime/nighttime based on sunset/sunrise times; however it seems that Tidbyt must already be determining this globally for the "dim at sunset" configuration.

Current approach:

```
resp = http.get("https://api.sunrise-sunset.org/json?lat=%f&lng=%f" % (loc.get("lat"), loc.get("lng")))
data = resp.body()
json_data = json.decode(data)
current_time=time.parse_time(now.format('3:04:05 PM'), format="3:04:05 PM", location=timezone)
sunrise=time.parse_time(json_data['results']['sunrise'], format="3:04:05 PM")
sunset=time.parse_time(json_data['results']['sunset'], format="3:04:05 PM")
color = color_nighttime
if current_time > sunrise and current_time < sunset:
    color = color_daytime
```

Exposing a "magic variable" (similar to `$tz` for timezone) could simplify this significantly and reduce API requests.

Suggested approach:

```
color = color_nighttime
if $is_daytime:
    color = color_daytime
```

**Comment by dinosaursrarr** [comment]
This was fixed by https://github.com/tidbyt/pixlet/pull/124 right?

**Comment by joeyhoer** [comment]
As a related request, I'm noticing that an abrupt change when "day" turns to "night" (and vice versa) in somewhat jarring. This could be resolved in the app by calculating some type of gradual transition; however, it could also be helpful to have variables for [the different types of twilight](https://www.timeanddate.com/astronomy/different-types-twilight.html)Civil twilight, Nautical twilight, and Astronomical twilight). This would provide app authors with the ability to slightly change colors to more accurately match ambient lighting without an physical light sensor connected to the Tidbyt (which would be a really cool hardware enhancement).

**Comment by dinosaursrarr** [comment]
@joeyhoer -- I have https://github.com/tidbyt/pixlet/pull/381 out at the moment which would let you do the maths. You could use sunrise.elevation_time to compute when the sun is at a certain angle below the horizon.

Or to use the sunrise.elevation function to determine whether it's currently day, civil, nautical, astronomical, or night for a given location.
