### ISSUE TITLE
.gitignore contains `.gif`

### ISSUE THREAD

**Issue by kcharwood** [tidbyt/community#483]
I noticed the .gitignore file excludes .gif files.

https://github.com/tidbyt/community/blob/9fe098e091d00d692845f3096734aeb678c03175/.gitignore#L27

This was weird to me since the authoring instructions include a step to generate a screenshot with a README. However, the .gitignore prevents the screenshot from getting committed unless it is saved as a different file format type.

I would either remove from the .gitignore, or update the authoring instructions if there is a specific reason it was decided to ignore .gifs

**Comment by rs7q5** [comment]
I believe the edition of the gif was a user mod to the readme. Fwiw, t's an optional step which I think the instructions say.
