### ISSUE TITLE
Reddit App: No images returned anymore

### ISSUE THREAD

**Issue by rs7q5** [tidbyt/community#501]
@N-Brooks here is where the reddit app is erroring out, when you return `rep.headers.get("Content-Type")` it returns `text/html`. 

https://github.com/tidbyt/community/blob/246b468bb7430830a3e866bdea9273ec082c6add/apps/redditimages/reddit_images.star#L144-L148

**Comment by rs7q5** [comment]
Update: looks like it's been blocked, will  need to figure out an issue around this.

**Comment by N-Brooks** [comment]
I've sent in a request to Reddit to see what I/we can do to get this unblocked. It's the Friday before a holiday weekend, though, so I don't expect any response until Tuesday.

**Comment by N-Brooks** [comment]
Wow, they got back to me fast!

> Thanks for your note!  With the information you've provided we've been able to view your app traffic in our logs, and we believe we know the root cause of the block.  I've filed an internal ticket for this, and we'll look into a resolution next week.

Looks like we just have to wait it out. Glad I didn't get blocked legitimately!

**Comment by rs7q5** [comment]
Awesome! Glad it's something they'll need to fix on their end
