### ISSUE TITLE
Wrong MLB Division Order

### ISSUE THREAD

**Issue by mcorby17** [tidbyt/community#651]
The MLB standings app has been showing the athletics in first for their division even though they're actually last. I saw this for the pirates as well in their division.

![Screenshot_20220911-092051.jpg](https://user-images.githubusercontent.com/12755405/189556421-e034b3d0-5262-4027-95b5-88bb105ac0e9.jpg)

**Comment by rs7q5** [comment]
Think this is supposed to be fixed with the merging of #649
