### ISSUE TITLE
build and test failing with unrelated app issues

### ISSUE THREAD

**Issue by jvivona** [tidbyt/community#693]
went to do a PR for a new app this morning and I'm seeing errors in build & test when it's trying to do a build of what looks like the SF Muni app
![image](https://user-images.githubusercontent.com/1454249/192267197-029e3f9b-b7f9-4c74-acf9-cdaf92d751da.png)

I see someone else's PR from this morning having the same issue.   

Anyone else seeing this?

**Comment by rs7q5** [comment]
It happens occasionally. if it has nothing to do with your app I usually don't worry about it. You should just check that none of the other files got changed except the ones that you actually messed with, but that's good practice anyways.
