### ISSUE TITLE
Textbyt app doesn't scroll when text goes off screen

### ISSUE THREAD

**Issue by mcorby17** [tidbyt/community#698]
https://user-images.githubusercontent.com/12755405/199616794-bce94dc2-85e9-475c-99c0-aad1f6948d58.mp4

**Comment by rs7q5** [comment]
Cc @joshareed

**Comment by joshareed** [comment]
Thanks for the bug report. The app is using a [Marquee with vertical scroll](https://github.com/tidbyt/community/blob/main/apps/textbyt/textbyt.star#L43-L52) setup, so I'm at a loss as to why it isn't working. I'll sign up as a beta tester to test it out myself.

**Comment by mcorby17** [comment]
Thanks for looking into it! Sorry I should have provided a screenshot. I'd do it now but I'm away from home for a week.

**Comment by mcorby17** [comment]
@joshareed hey I tested it today and it scrolled so I guess the problem is resolved 😅

**Comment by mcorby17** [comment]
@joshareed I saw it happen again. I think it depends on how long the message is, if it's long enough to go off the screen but not long enough to go off the container for the text then it doesn't scroll.

Try playing around with different text lengths. Here is the text I sent that made it fail to scroll:

Hiiii I love you and hope you're having a great day!! :)

**Comment by joshareed** [comment]
Thanks for the tip. I've got it installed and I'll try reproducing it. I probably forgot to shrink the height of the marquee to account for the name header.
