### ISSUE TITLE
Tidbyt Gif folder?

### ISSUE THREAD

**Issue by Eastonco** [tidbyt/community#76]
What are your thoughts on adding a folder for gifs specifically designed for tidbyt? While apps like the Nyan cat look great, realistically a lot of similar animations don't need full fledged apps and could instead be stored in a folder of gifs for people to download and install via the images app. Obviously keep the iconic ones (like nyan cat) but an additional library to look through could make a great addition to the repo

**Comment by mackorone** [comment]
> keep the iconic ones

For what it's worth, I'd be totally fine with merging the Nyan Cat app into a single app or library for all GIFs.
