### ISSUE TITLE
Refresh rate of published apps

### ISSUE THREAD

**Issue by humanapp** [tidbyt/community#832]
Are apps published to the community server refreshed automatically? As in, is the .star file re-executed at a regular interval and the resulting webp pushed to devices where the app is installed?

If they are auto-refreshed, what is the frequency? If not auto-refreshed, how do apps like clock, weather, and symbol tickers update?

I couldn't find the answer in the documentation.

**Comment by rs7q5** [comment]
I presume you mean refreshed in the app. If so, yes,but all apps share the same cache key. So update of data is based on the expiration of that key. I believe the apps run right before they are about to come around on your device and the webp is updated.

So basically though the refresh of new data displayed is usually based on when new data was grabbed. 

There is a known clock skew, that does seem to be better now, but a discussion can be found [here](https://discuss.tidbyt.com/t/clock-skew/2571) though. 

Hope this helps.
