### ISSUE TITLE
"Games behind" sorting is broken for the "NFL Standings" App 

### ISSUE THREAD

**Issue by petersbattaglia** [tidbyt/community#854]
![thumbnail_image0](https://user-images.githubusercontent.com/1198341/205550998-1eaa8a07-5dc2-4684-b47f-c4765b6f2833.png)

See above image. The current Week 13 stats show this for the AFC South. Houston should be at the bottom.

**Comment by rs7q5** [comment]
Cc @cmarkham20

**Comment by cmarkham20** [comment]
I noticed that this morning... Should be fixed in https://github.com/tidbyt/community/pull/860/
