### ISSUE TITLE
tidybyt/community  GitHub Workflow check for print statements

### ISSUE THREAD

**Issue by jvivona** [tidbyt/community#911]
is there a way to get the workflow to check that print statements aren't in the published app to prevent unnecessary data in the build logs / workflow logs?

**Comment by rs7q5** [comment]
I don't think having some print statements present is necessarily a bad thing. But if you have tons you could create a debug variable and set to false in the community app and change in production worst case if you don't want to just comment them out.

**Comment by jvivona** [comment]
or (and I don't know if this is possible) - shunt that output during compile/test in the workflow so it doesn't flood the github logs.

**Comment by rs7q5** [comment]
So I'm sure it is possible, but even if it doesn't flood the github logs, I think it would still flood their logs on their servers? 

I was simply giving you an alternative if you wanted at least a quicker temporary fix if this is possible to do. Not having to worry about commenting them out would be nice though, I don't disagree.

**Comment by jvivona** [comment]
I don't typically leave them in code I submit - I use it for debugging & then delete them.   But I see other folks still have them.  was helping someone else out with a failed test & I had to weed through a bunch of another submitter's app debugging/print to find the error in the app we were working on.   Just trying to streamline it as a general rule.     we're on the same page.

**Comment by rs7q5** [comment]
Yeah, I'm with you if they are super useful and beyond just hit or miss on the api, usually they get commented out or just deleted. 

But agreed, wading through those is a pita.
