### ISSUE TITLE
weathermap: hitting render_error

### ISSUE THREAD

**Issue by heyshiloh** [tidbyt/community#932]
## Issue
Issue is described in title, just wanted to give a heads up because I enjoy this app! 
`"Error loading weather maps!"`

## Steps to reproduce
`On app load`

reading through your code I can't imagine why this would be a [frame rendering error](https://github.com/tidbyt/community/blob/f7f01cd41a7d54f6201d129379d396d0a639a605/apps/weathermap/weather_map.star#L376) as it was working last night, so I would guess that it could be an [api response error](https://github.com/tidbyt/community/blob/f7f01cd41a7d54f6201d129379d396d0a639a605/apps/weathermap/weather_map.star#L356).

great work on this app and see you all in future PRs!

**Comment by rs7q5** [comment]
cc @fxb

**Comment by heyshiloh** [comment]
looks like it got fixed one way or another
